### ISSUE TITLE
重构郑重声明！！！

### ISSUE THREAD

**Issue by cuisongliu** [labring/endpoints-operator#132]
下面将会引来此项目一个具体的革新。

其实最初这个项目为了解决外部服务的特性，沿用了service和endpoint的能力，从而达到可以读取集群外部服务的能力。但是慢慢的发现，它并不能达到一些有状态服务的能力。其中的原因就是service和endpoint的定义只能定义相同的端口，无法使用不同的端口最为后端地址。为了实现这个功能，其实就是要做到实现headless的能力，所以决定废弃这个设计。重新设计一个新的operaotor。

1. 复用一部分lvscare的能力直接透传ipvs的能力，后端自由化，可以随意组合。
2. 每个ClusterIP都有自己独特探活能力，支持TCP UDP GRPC HTTP等
3. 支持自动domain能力

最终： 你可以把有状态服务接入进来，而且你并不需要所有的host有相同的端口，这个能力很重要。将来你可以借助这个能力实现外部中间件内部负载的能力。无需担心中间件云上不同集群访问的问题了。

**Comment by cuisongliu** [comment]
1. 给对应的redis创建service 配置

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    monitor.kubeblocks.io/agamotto: "false"
    monitor.kubeblocks.io/scrape: "false"
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubeblocks
    app.kubernetes.io/name: redis
    apps.kubeblocks.io/component-name: redis
  name: redis-redis-headless-p0
  namespace: redis-cloud
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubeblocks
    apps.kubeblocks.io/component-name: redis
    statefulset.kubernetes.io/pod-name: redis-redis-0
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    monitor.kubeblocks.io/agamotto: "false"
    monitor.kubeblocks.io/scrape: "false"
  labels:
    app.kubernetes.io/component: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubeblocks
    app.kubernetes.io/name: redis
    apps.kubeblocks.io/component-name: redis
  name: redis-redis-headless-p1
  namespace: redis-cloud
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubeblocks
    apps.kubeblocks.io/component-name: redis
    statefulset.kubernetes.io/pod-name: redis-redis-1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    monitor.kubeblocks.io/agamotto: "false"
    monitor.kubeblocks.io/scrape: "false"
  labels:
    app.kubernetes.io/component: redis-sentinel
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubeblocks
    app.kubernetes.io/name: redis
    apps.kubeblocks.io/component-name: redis-sentinel
  name: redis-redis-sentinel-headless-p0
  namespace: redis-cloud
spec:
  ports:
  - name: redis-sentinel
    port: 26379
    protocol: TCP
    targetPort: redis-sentinel
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubeblocks
    apps.kubeblocks.io/component-name: redis-sentinel
    statefulset.kubernetes.io/pod-name: redis-redis-sentinel-0
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    monitor.kubeblocks.io/agamotto: "false"
    monitor.kubeblocks.io/scrape: "false"
  labels:
    app.kubernetes.io/component: redis-sentinel
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubeblocks
    app.kubernetes.io/name: redis
    apps.kubeblocks.io/component-name: redis-sentinel
  name: redis-redis-sentinel-headless-p1
  namespace: redis-cloud
spec:
  ports:
  - name: redis-sentinel
    port: 26379
    protocol: TCP
    targetPort: redis-sentinel
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubeblocks
    apps.kubeblocks.io/component-name: redis-sentinel
    statefulset.kubernetes.io/pod-name: redis-redis-sentinel-1
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    monitor.kubeblocks.io/agamotto: "false"
    monitor.kubeblocks.io/scrape: "false"
  labels:
    app.kubernetes.io/component: redis-sentinel
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubeblocks
    app.kubernetes.io/name: redis
    apps.kubeblocks.io/component-name: redis-sentinel
  name: redis-redis-sentinel-headless-p2
  namespace: redis-cloud
spec:
  ports:
  - name: redis-sentinel
    port: 26379
    protocol: TCP
    targetPort: redis-sentinel
  selector:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kubeblocks
    apps.kubeblocks.io/component-name: redis-sentinel
    statefulset.kubernetes.io/pod-name: redis-redis-sentinel-2
  type: NodePort
status:
  loadBalancer: {}

```
